//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAlisverisOtomasyonu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnlineAlisveriVT1Entities : DbContext
    {
        public OnlineAlisveriVT1Entities()
            : base("name=OnlineAlisveriVT1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminler> Adminler { get; set; }
        public virtual DbSet<Kargo> Kargo { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Odeme> Odeme { get; set; }
        public virtual DbSet<OdemeTurleri> OdemeTurleri { get; set; }
        public virtual DbSet<SilinenMusteri> SilinenMusteri { get; set; }
        public virtual DbSet<SilinenUrunler> SilinenUrunler { get; set; }
        public virtual DbSet<SiparisDetaylari> SiparisDetaylari { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<Siparisler1> Siparisler1 { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<UrunRenkleri> UrunRenkleri { get; set; }
    
        public virtual ObjectResult<AdARA_Result> AdARA(string ad)
        {
            var adParameter = ad != null ?
                new ObjectParameter("ad", ad) :
                new ObjectParameter("ad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdARA_Result>("AdARA", adParameter);
        }
    
        public virtual ObjectResult<FiyataGöreAra_Result> FiyataGöreAra(Nullable<decimal> para)
        {
            var paraParameter = para.HasValue ?
                new ObjectParameter("para", para) :
                new ObjectParameter("para", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FiyataGöreAra_Result>("FiyataGöreAra", paraParameter);
        }
    
        public virtual ObjectResult<FiyataGöreAra1_Result> FiyataGöreAra1(Nullable<decimal> para)
        {
            var paraParameter = para.HasValue ?
                new ObjectParameter("para", para) :
                new ObjectParameter("para", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FiyataGöreAra1_Result>("FiyataGöreAra1", paraParameter);
        }
    
        public virtual ObjectResult<MusteriAdiAra_Result> MusteriAdiAra(string musteriAdi)
        {
            var musteriAdiParameter = musteriAdi != null ?
                new ObjectParameter("musteriAdi", musteriAdi) :
                new ObjectParameter("musteriAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MusteriAdiAra_Result>("MusteriAdiAra", musteriAdiParameter);
        }
    
        public virtual ObjectResult<MusteriAra_Result> MusteriAra(string musteriAdi)
        {
            var musteriAdiParameter = musteriAdi != null ?
                new ObjectParameter("musteriAdi", musteriAdi) :
                new ObjectParameter("musteriAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MusteriAra_Result>("MusteriAra", musteriAdiParameter);
        }
    
        public virtual ObjectResult<RenkliUrun_Result> RenkliUrun(string renk)
        {
            var renkParameter = renk != null ?
                new ObjectParameter("renk", renk) :
                new ObjectParameter("renk", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RenkliUrun_Result>("RenkliUrun", renkParameter);
        }
    
        public virtual ObjectResult<UrunAdiAra_Result> UrunAdiAra(string urunAdi)
        {
            var urunAdiParameter = urunAdi != null ?
                new ObjectParameter("urunAdi", urunAdi) :
                new ObjectParameter("urunAdi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UrunAdiAra_Result>("UrunAdiAra", urunAdiParameter);
        }
    }
}
