//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAlisverisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odeme
    {
        public int OdemeID { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public Nullable<System.DateTime> OdemeTarihi { get; set; }
        public string OdemeTuru { get; set; }
        public Nullable<decimal> OdemeTutari { get; set; }
        public Nullable<int> OdemeTuruID { get; set; }
    
        public virtual OdemeTurleri OdemeTurleri { get; set; }
        public virtual Siparisler Siparisler { get; set; }
    }
}
