//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAlisverisOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class SilinenMusteri
    {
        public int SilinenMusteriID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<System.DateTime> SilinmeTarihi { get; set; }
        public string SilenAdmin { get; set; }
    }
}
